catalogMode: prefer
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - pnpm@11.18.0
  - publint@0.3.22
  - tsdown@0.22.14

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^9.2.0
    '@antfu/ni': ^30.3.0
    bumpp: ^12.1.1
    eslint: ^10.8.0
    pnpm: ^11.18.0
    publint: ^0.3.22
    tsdown: ^0.22.14
    tsx: ^4.23.1
    typescript: ^5.9.3
    vite: ^8.1.5
  deps:
    js-tokens: ^10.0.0
  testing:
    three: ^0.185.1
    vitest: ^4.1.10
    vue: ^3.5.40
  types:
    '@types/node': ^26.1.2

allowBuilds:
  esbuild: true
